### ISSUE TITLE
Update for go driver

### ISSUE THREAD

**Issue by tudorels** [djondb/djondbgo#1]
Hello, I want to use djondb with golang, but I saw the driver is from 2013. Is there a chance to be updated in the future, to benefit from all functionalities of new versions of djondb?
Thank you!

**Comment by crossleyjuan** [comment]
Hello, sure, may i ask you when do you need it ready? So i can prepare my time and have it ready for you?

**Comment by tudorels** [comment]
Is not very big hurry, I started doing some tests and it seems djondb is well suited for a project that will begin in two months maybe more.I wanted to know if I can count on an updated driver for development.
So we can wait a period for the driver to be ready.
Thank you very much!

**Comment by djondb** [comment]
Sure thing, it'll take no time, I'll update it next weekend

Thanks

**Comment by crossleyjuan** [comment]
70% completed, tomorrow night I'll have the driver ready for testing,

**Comment by tudorels** [comment]
I'm glad to hear that.

**Comment by crossleyjuan** [comment]
Hello tudorels,
The driver is now completed and ready to work, I've created several test methods and all of them passed, please let me know if you have any problems, I've also updated the documentation.

**Comment by tudorels** [comment]
Hello, I will soon begin to use it and let you know if I have problems. Thank you!
